version: '3'

services:
  django:
    build:
      context: ..
      dockerfile: ./compose/django/Dockerfile
    env_file: ../dev.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foolish-pg-pass
      - POSTGRES_USER=foolish-user
      - POSTGRES_DB=foolish_db
