services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foolish-pg-pass
      - POSTGRES_USER=foolish-user
      - POSTGRES_DB=foolish_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - foolish-network
  django:
    container_name: django
    build:
      context: ..
      dockerfile: django/dev.backend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - foolish-network
networks:
  foolish-network:
    driver: bridge
